GET http://localhost:3001/employee/

### 

POST http://localhost:3001/employee/
Content-Type: application/json 

{
    "id":1,
    "name":"tata",
    "age" : 40,
    "salary":30000
}

### 
PUT http://localhost:3001/employee/1/
Content-Type: application/json 

{
    "id":7,
    "name":"gopi",
    "age" : 46,
    "salary":440000
}

### 
DELETE http://localhost:3001/employee/7/

{
    "id":7
}